name: My first workflow

# Here we specify what event in github triggers the execution of the workflow.
on: push

# A workflow consists of one or more jobs.
# A job is a unit of work that runs on a single machine
jobs:
  my_first_job:
    runs-on: ubuntu-latest # specify the OS for our machine.

    # The individual instructions that define a job.
    steps:
      - name: Print a dumb greeting
        run: echo 'Hello world'
      - name: A simple calculator
        env:
          TWO: 2
        run: |
          SUM=$(($TWO + $TWO))
          echo 'two and two makes' $SUM

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
