name: My first workflow

# Here we specify what event in github triggers the execution of the workflow.
on: push

# A workflow consists of one or more jobs.
# A job is a unit of work that runs on a single machine
jobs:
  my_first_job:
    runs-on: ubuntu-latest # specify the OS for our machine.

    # The individual instructions that define a job.
    steps:
      - name: Print a dumb greeting
        run: echo 'Hello world'
      - name: A simple calculator
        env:
          TWO: 2
        run: |
          SUM=$(($TWO + $TWO))
          echo 'two and two makes' $SUM

  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: gh_action_demo_test
        ports:
            - 33306:3306

    steps:
      - uses: actions/checkout@v1

      - name: Set up RVM
        run: curl -sSL https://get.rvm.io | bash

      - name: Set up a custom Ruby
        env:
          RUBY_VERSION: 2.4.9
        run: |
          source $HOME/.rvm/scripts/rvm
          rvm install $RUBY_VERSION --binary
          rvm --default use $RUBY_VERSION

      - name: Build App
        env:
          DB_HOST: localhost
          DB_USER: root
          DB_PWD: root
          RAILS_ENV: test
        run: |
          source $HOME/.rvm/scripts/rvm
          gem install bundler
          bundle install --jobs 4 --retry 3
          bin/rails db:test:prepare RAILS_ENV=$RAILS_ENV
#
#      - name: Run Tests
#        env:
#          DB_HOST: localhost
#          DB_USER: root
#          DB_PWD: root
#          RAILS_ENV: test
#        run: |
#          source $HOME/.rvm/scripts/rvm
#          bundle exec rails t
